config/routes.rb
Fbcollector::Application.routes.draw do
  root :to => 'annotations#new'

  match 'privacy' => 'annotations#privacy'

  resources :users
  resources :annotations

end

app/models/annotation.rb
class Annotation < ActiveRecord::Base
  attr_accessible :facebook_name, :facebook_id, :month, :year, :day

  #validates_numericality_of :day, :on => :create, :only_integer => true, :greater_than => 0, :less_than_or_equal_to => 31
  #validates_numericality_of :month, :on => :create, :only_integer => true, :greater_than => 0, :less_than_or_equal_to => 12
  #validates_numericality_of :year, :on => :create, :only_integer => true, :greater_than => 0
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :message, :facebook_created_at, :facebook_id, :from, :likes, :to

  validates_uniqueness_of :facebook_id

  #belongs_to :message
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :facebook_id, :tag_count, :like_count, :comment_count, :content, :from, :to, :post_type, :facebook_created_time, :facebook_updated_time, :recipient_is_tagged, :comments_attributes, :application_name, :has_link, :has_video, :has_with_tag, :has_place

  validates_uniqueness_of :facebook_id

  has_many :comments
  accepts_nested_attributes_for :comments
end

app/models/response_log.rb
class ResponseLog < ActiveRecord::Base
  attr_accessible :content
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :facebook_id, :location_id, :location_name, :gender, :timezone, :locale, :birthday, :friend_of

  validates_uniqueness_of :facebook_id
end

app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController
  before_filter :parse_facebook_cookies

  def parse_facebook_cookies
    @facebook_cookies ||= Koala::Facebook::OAuth.new.get_user_info_from_cookie(cookies)
  end

  def privacy
  end

  # GET /annotations/new
  # GET /annotations/new.json
  def new
    unless @facebook_cookies.nil? || cookies[:facebook_completed]
      Delayed::Job.enqueue ::Parser.new(@facebook_cookies["access_token"])
      cookies[:facebook_completed] = true
    end

    @annotation = Annotation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @annotation }
    end
  end

  # POST /annotations
  # POST /annotations.json
  def create
    @annotation = Annotation.create!(params[:annotation])
    cookies[:completed] = { :value => true, :expires => 1.year.from_now }

    respond_to do |format|
      format.html { redirect_to '/' }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/annotations_helper.rb
module AnnotationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/annotations/_form.html.erb
<%= form_for(@annotation) do |f| %>
  <% if @annotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@annotation.errors.count, "error") %> prohibited this annotation from being saved:</h2>

      <ul>
      <% @annotation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <thead>
      <th>Name</th>
      <th>Year</th>
      <th>Month</th>
      <th>Day</th>
    </thead>
    <tbody id="user_list">
      <tr>
        <td><input class="annotation_facebook_name" name="annotation[][facebook_name]" type="text"><input class="annotation_facebook_id" name="annotation[][facebook_id]" type="hidden"></td>
        <td class="slim"><input class="number annotation_year" name="annotation[][year]" placeholder="eg. 2008" type="number" min="0"></td>
        <td class="slim"><input class="number annotation_month" name="annotation[][month]" placeholder="eg. 12" type="number" min="0" max="12"></td>
        <td class="slim"><input class="number annotation_day" name="annotation[][day]" placeholder="eg. 31" type="number" min="0" max="31"></td>
      </tr>
    </tbody>
  </table>

  <div class="actions">
    <input name="commit" type="submit" value="Submit &rarr;" style="width: inherit;">
  </div>
<% end %>

app/views/annotations/edit.html.erb
<h1>Editing annotation</h1>

<%= render 'form' %>

<%= link_to 'Show', @annotation %> |
<%= link_to 'Back', annotations_path %>

app/views/annotations/new.html.erb
<h1>Know a Facebook user that recently deceased?</h1>

<p class="large"><strong>Donate your Facebook data to science.</strong> Your data will be used to better understand interaction patterns with deceased users on Facebook.</p>

<section id="set-in">
  <% if defined?(cookies[:completed]) && cookies[:completed] %>
    <div id="thankyou-container">
      <h3>Thank you!</h3>
    </div>
  <% else %>
    <% unless notice.nil? %>
      <p id="notice"><%= notice %></p>
    <% end %>

    <% unless @facebook_cookies.nil? %>
      <p id="notice">Please tag the appropriate users and enter a death date. Be as specific as possible, but leave empty fields if you are uncertain.</p>
    <% end %>
    <div id="setin-container">
      <% if @facebook_cookies.nil? %>
        <div class="fb-button-container">
          <a class="fb-button" id="auth-loginlink" href="">
            <span class="fb-button-left"></span>
            <span class="fb-button-center"><strong>Log in</strong> with <strong>Facebook</strong></span>
            <span class="fb-button-right"></span>
          </a>
          <div style="clear: both"></div>
        </div>
      <% else %>
        <%= render 'form' %>
      <% end %>
    <% end %>
  </div>
</section>

app/views/annotations/privacy.html.erb
<h1>Privacy Policy</h1>
<div class="smalltype">

<p><strong>Note that the collected data is anonymized: name, location, email, profile pictures, etc. are not stored.</strong> The source code of this app is made available <a href="">here</a> for public scrutiny. </p>

<p>While humans may occasionally browse the data, the collected data is intended to be consumed by special computer programs that automatically find relevant patterns.</p>

<p>All your individual friend feeds are collected by this app, but only the following data is retained: </p>

<ul>
  <li>User data, including Facebook ID, language (locale), birthday (when available) and gender.</li>
  <li>All historial posts, including post type, number of tags, number of likes, comments and timestamp.</li>
</ul>

<p>Aside from other researchers working on this project, this data will not be shared with third parties. Any concerns should be addressed to David Chouinard at <a href="mailto:david@tedxmontreal.com">david@tedxmontreal.com</a>.</p>

<h2>About the Research Project</h2>
<p>As the quantity of online personal data grows at an astounding pace, death and preservation of digital assets pose increasingly important problems. Online troves of email messages, blog postings or Facebook photos are often precious to the family members of deceased users.</p>
<p>Currently, there is no way to systematically and reliably determine the death of an online user. Consequently, most service providers simply delete old, inactive accounts. If one could detect the death of a user, measures could be taken by a third party to permanently archive user data.</p>
<p>This project explores the development of a computational model to precisely and accurately detect death by analyzing Facebook interactions. Indeed, messages sent in response to the passing of a user have very characteristic content and a distinctive timing signature.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Know a Facebook user that recently deceased?</title>
  <%= javascript_include_tag "//use.typekit.com/gkp5vyd.js" %>
  <script>try{Typekit.load();}catch(e){}</script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if !IE 7]>
  <style type="text/css">
    #wrap {display:table;height:100%}
  </style>
  <![endif]-->
</head>
<body>

<div id="fb-root"></div>
<script>
  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));

  window.fbAsyncInit = function() {
    FB.init({
      appId      : '<%= Facebook::APP_ID %>', // App ID
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });

    // respond to clicks on the login and logout links
    $('#auth-loginlink').on('click', function(e) {
      e.preventDefault();
      FB.login(function(response) {
        if (response.authResponse) {
          // user is logged into Facebook, reload the page
          window.location.reload();
        }
      }, {scope: 'user_status,friends_status,user_birthday,friends_birthday,read_stream'});
    });

    FB.Event.subscribe('auth.statusChange', function(response) {
      if (response.authResponse) {
        FB.api('/me/friends', function(result) {
          friends = _.map(result.data, function(friend) { return {"label": friend.name, "id":friend.id} });
          $('.annotation_facebook_name').autocomplete({
            source: friends,
            select: function(event, ui) {
              $(this).siblings('.annotation_facebook_id').val(ui.item.id);
            }
          })
        });
      }
    });
  };

</script>

<div id="wrap">
  <div id="main">
    <%= yield %>
  </div>
</div>

<footer>
  <p><a href="/privacy">What data does this app collect?</a></p>
  <p>This research is conducted at Concordia University by David Chouinard under the supervision of Dr. Sabine Bergler.</p>
</footer>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :facebook_id %><br />
    <%= f.text_field :facebook_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Facebook</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.facebook_id %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Facebook:</b>
  <%= @user.facebook_id %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>